---
deployment:
  tasks:
    - export REPOPATH=/home/coincard/repositories/coin-card
    - export APPPATH=/home/coincard/coin-card_app
    - export PUBLICPATH=/home/coincard/public_html

    - /bin/mkdir -p $APPPATH
    - /usr/bin/rsync -a --delete \
        --exclude ".git/" \
        --exclude ".cpanel.yml" \
        --exclude ".env" \
        $REPOPATH/ $APPPATH/

    - /usr/bin/rsync -a --delete $APPPATH/public/ $PUBLICPATH/
